# Generated by Django 5.1.3 on 2025-07-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpikeZoneApiApp', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
