# Generated by Django 5.1.3 on 2025-07-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpikeZoneApiApp', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='SpikeZoneApiApp.order'),
        ),
    ]
