# Generated by Django 5.1.3 on 2025-08-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpikeZoneApiApp', '0008_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='hi', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
