"""
Django settings for SpikeZoneApi project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import posixpath
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SEO_JSON_DIR = os.path.join(BASE_DIR, 'SpikeZoneApiApp', 'media')

# All secrets and environment-specific values live in .env (see .env.example)
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'unsafe-dev-only-key')

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'SpikeZoneApiApp',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SpikeZoneApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SpikeZoneApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# MySQL everywhere that matters. DB_ENGINE=sqlite is a local-development
# escape hatch for working on the app without a MySQL server to hand - it is
# never set in production, where leaving the variable out gives MySQL.
if os.environ.get('DB_ENGINE', 'mysql').lower() == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'spikezoneapi'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }

RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'
# MEDIA_ROOT = 'D:/New Datsa/spikezone/SpikeZoneApi/Uploads/products/'
# MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'SpikeZoneApiApp.User'


REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # Only the OTP endpoints opt into throttling, via the scopes below.
    'DEFAULT_THROTTLE_RATES': {
        # Per recipient (phone number / email address), not per IP - see
        # SpikeZoneApiApp.auth_views.OTPTargetThrottle. Every phone OTP is a
        # billable SMS, so this rate is the ceiling on what a single number
        # can cost us in an hour.
        'otp_target': '5/hour',
        # Verifying costs nothing and legitimate users do fumble a code, so
        # the check is looser. Brute force is bounded by EmailOTP.MAX_ATTEMPTS
        # per issued code rather than by this rate.
        'otp_target_verify': '20/hour',
    },

}

# Which OTP provider the phone-login endpoints use. 'firebase' is the only one
# registered today; the indirection exists so a move to a direct Indian SMS
# gateway (worth it somewhere north of ~15k OTPs/month, once DLT registration
# has paid for itself) is a config change rather than a code change.
OTP_PROVIDER = os.environ.get('OTP_PROVIDER', 'firebase')

# Throttle counters live in the cache. LocMemCache is per-process, so with N
# Passenger workers the effective ceiling is N x the configured rate - still
# bounded, but if the SMS bill ever needs a hard limit, point this at Redis or
# Django's DatabaseCache (which is shared across workers).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'spikezone-default',
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',

}

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:9898",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://192.168.1.35:3000",
]

# SMTP everywhere real. Local development can set EMAIL_BACKEND to
# django.core.mail.backends.console.EmailBackend to print OTP mails to the
# runserver console instead of needing live mail credentials.
# `or` rather than a default argument: a key that is present but empty
# (EMAIL_BACKEND= in .env, which is how the production template ships it)
# would otherwise be used verbatim as the import path and blow up with
# "doesn't look like a module path" the first time anything sends mail.
EMAIL_BACKEND = (
    os.environ.get('EMAIL_BACKEND', '').strip()
    or 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_TLS = not EMAIL_USE_SSL and EMAIL_PORT == 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

CORS_ORIGIN_ALLOW_ALL = True

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]


# ---------------------------------------------------------------------------
# Production hardening
#
# All of this is gated on DEBUG so local development over plain http keeps
# working - switching these on locally would redirect http://127.0.0.1:8001 to
# https and drop the session cookie.
# ---------------------------------------------------------------------------
if not DEBUG:
    # Apache/Passenger terminates TLS and forwards the original scheme in this
    # header. Without it Django thinks every request arrived over http and
    # SECURE_SSL_REDIRECT below turns into an infinite redirect loop.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Set DJANGO_SECURE_SSL_REDIRECT=False if the host already redirects to
    # https itself - doing it in both places is what causes redirect loops.
    SECURE_SSL_REDIRECT = os.environ.get(
        'DJANGO_SECURE_SSL_REDIRECT', 'True'
    ).lower() in ('true', '1', 'yes')

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS tells browsers to refuse plain http for this domain, and they cache
    # that for max-age - so a mistake here is not quickly undone. Left off by
    # default; once https is confirmed working on every subdomain, ramp it up
    # (start around 3600, then a week, then a year).
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '0'))
    if SECURE_HSTS_SECONDS:
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = False


# STATIC_ROOT = BASE_DIR / "staticfiles"

# MEDIA_URL = "/media/"

# MEDIA_ROOT = BASE_DIR / "media"
